### ISSUE TITLE
Importing events from only current agenda span

### ISSUE THREAD

**Issue by xenomorph1096** [abstern/khalel#1]
Hi!
Firstly, thanks for writing such a nice package!
I tried a lot of other stuff, like org-caldav, etc, and none of them really worked well for me. 

Your package works pretty well for me, and I intend to start using it as my daily driver. Lets see how it goes. 

I thought that it would be nice that the list of events imported from khal depends on the start and end date currently displayed by org-agenda. This also would be useful since I am usually in the week view, and events from previous days in the week are not visible for me.

I have forked your repo and implemented this stuff. Pull request will follow.

**Comment by hperrey** [comment]
Hej!
Original author here -- thanks for the kind words! I hope you still find khalel useful as a daily driver! :)

I thought I'd let you know that this is not the main repository for the code though but an inoffical mirror that lags behind the current state of khalel. You can find the current version here: https://gitlab.com/hperrey/khalel

I'd happy to discuss any PR or FR there!

Best,
Hanno

**Comment by xenomorph1096** [comment]
Thanks a lot for the heads up! See you on gitlab!
